number=int(input("Number: "))
sum= int(str(number)[0])+int(str(number)[1])+int(str(number)[2])
print("Sum= ", sum)
umnog= int(str(number)[0])*int(str(number)[1])*int(str(number)[2])
print("Umnogenie= ", umnog)